[2024-09-11T04:51:46.042+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T04:51:46.059+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: http_test_dag.post_op manual__2024-09-11T04:51:13.394793+00:00 [queued]>
[2024-09-11T04:51:46.068+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: http_test_dag.post_op manual__2024-09-11T04:51:13.394793+00:00 [queued]>
[2024-09-11T04:51:46.069+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T04:51:46.428+0000] {taskinstance.py:2888} INFO - Executing <Task(HttpOperator): post_op> on 2024-09-11 04:51:13.394793+00:00
[2024-09-11T04:51:46.436+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=109) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-11T04:51:46.439+0000] {standard_task_runner.py:72} INFO - Started process 111 to run task
[2024-09-11T04:51:46.439+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'http_test_dag', 'post_op', 'manual__2024-09-11T04:51:13.394793+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/http_test_dag.py', '--cfg-path', '/tmp/tmpvmi76k8m']
[2024-09-11T04:51:46.441+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask post_op
[2024-09-11T04:51:46.572+0000] {task_command.py:467} INFO - Running <TaskInstance: http_test_dag.post_op manual__2024-09-11T04:51:13.394793+00:00 [running]> on host 4effec9919e9
[2024-09-11T04:51:46.834+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='http_test_dag' AIRFLOW_CTX_TASK_ID='post_op' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T04:51:13.394793+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T04:51:13.394793+00:00'
[2024-09-11T04:51:46.837+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-11T04:51:46.837+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-11T04:51:46.837+0000] {logging_mixin.py:190} INFO - Current task name:post_op state:running start_date:2024-09-11 04:51:46.060723+00:00
[2024-09-11T04:51:46.838+0000] {logging_mixin.py:190} INFO - Dag name:http_test_dag and current dag run status:running
[2024-09-11T04:51:46.838+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T04:51:46.838+0000] {http.py:173} INFO - Calling HTTP method
[2024-09-11T04:51:46.847+0000] {base.py:84} INFO - Retrieving connection 'my_http_connection'
[2024-09-11T04:51:46.854+0000] {base.py:84} INFO - Retrieving connection 'my_http_connection'
[2024-09-11T04:51:47.341+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 170, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 181, in execute_sync
    return self.process_response(context=context, response=response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 225, in process_response
    if not self.response_check(response, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/http_test_dag.py", line 46, in <lambda>
    response_check=lambda response: response.json()["json"]["priority"] == 5,
                                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-09-11T04:51:47.359+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-11T04:51:47.360+0000] {logging_mixin.py:190} INFO - Task start:2024-09-11 04:51:46.060723+00:00 end:2024-09-11 04:51:47.358907+00:00 duration:1.298184
[2024-09-11T04:51:47.361+0000] {logging_mixin.py:190} INFO - Task:<Task(HttpOperator): post_op> dag:<DAG: http_test_dag> dagrun:<DagRun http_test_dag @ 2024-09-11 04:51:13.394793+00:00: manual__2024-09-11T04:51:13.394793+00:00, state:running, queued_at: 2024-09-11 04:51:13.413527+00:00. externally triggered: True>
[2024-09-11T04:51:47.362+0000] {logging_mixin.py:190} INFO - Failure caused by Expecting value: line 1 column 1 (char 0)
[2024-09-11T04:51:47.363+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=http_test_dag, task_id=post_op, run_id=manual__2024-09-11T04:51:13.394793+00:00, execution_date=20240911T045113, start_date=20240911T045146, end_date=20240911T045147
[2024-09-11T04:51:47.517+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T04:51:47.518+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task post_op (Expecting value: line 1 column 1 (char 0); 111)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 170, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 181, in execute_sync
    return self.process_response(context=context, response=response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 225, in process_response
    if not self.response_check(response, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/http_test_dag.py", line 46, in <lambda>
    response_check=lambda response: response.json()["json"]["priority"] == 5,
                                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-09-11T04:51:47.564+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-11T04:51:47.579+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T04:51:47.750+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
