[2024-09-11T04:12:23.319+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T04:12:23.340+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: http_test_dag.get_op manual__2024-09-11T04:12:17.707731+00:00 [queued]>
[2024-09-11T04:12:23.352+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: http_test_dag.get_op manual__2024-09-11T04:12:17.707731+00:00 [queued]>
[2024-09-11T04:12:23.353+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T04:12:23.552+0000] {taskinstance.py:2888} INFO - Executing <Task(HttpOperator): get_op> on 2024-09-11 04:12:17.707731+00:00
[2024-09-11T04:12:23.563+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'http_test_dag', 'get_op', 'manual__2024-09-11T04:12:17.707731+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/http_test_dag.py', '--cfg-path', '/tmp/tmpt0u7ea99']
[2024-09-11T04:12:23.567+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask get_op
[2024-09-11T04:12:23.569+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-11T04:12:23.570+0000] {standard_task_runner.py:72} INFO - Started process 324 to run task
[2024-09-11T04:12:23.764+0000] {task_command.py:467} INFO - Running <TaskInstance: http_test_dag.get_op manual__2024-09-11T04:12:17.707731+00:00 [running]> on host 665b592a4e82
[2024-09-11T04:12:24.760+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='http_test_dag' AIRFLOW_CTX_TASK_ID='get_op' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T04:12:17.707731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T04:12:17.707731+00:00'
[2024-09-11T04:12:24.763+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-11T04:12:24.764+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-11T04:12:24.764+0000] {logging_mixin.py:190} INFO - Current task name:get_op state:running start_date:2024-09-11 04:12:23.341083+00:00
[2024-09-11T04:12:24.765+0000] {logging_mixin.py:190} INFO - Dag name:http_test_dag and current dag run status:running
[2024-09-11T04:12:24.765+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T04:12:24.765+0000] {http.py:173} INFO - Calling HTTP method
[2024-09-11T04:12:24.789+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 170, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 179, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 152, in hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `http_default` isn't defined
[2024-09-11T04:12:25.522+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-11T04:12:25.524+0000] {logging_mixin.py:190} INFO - Task start:2024-09-11 04:12:23.341083+00:00 end:2024-09-11 04:12:25.521608+00:00 duration:2.180525
[2024-09-11T04:12:25.524+0000] {logging_mixin.py:190} INFO - Task:<Task(HttpOperator): get_op> dag:<DAG: http_test_dag> dagrun:<DagRun http_test_dag @ 2024-09-11 04:12:17.707731+00:00: manual__2024-09-11T04:12:17.707731+00:00, state:running, queued_at: 2024-09-11 04:12:17.743167+00:00. externally triggered: True>
[2024-09-11T04:12:25.525+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `http_default` isn't defined
[2024-09-11T04:12:25.526+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=http_test_dag, task_id=get_op, run_id=manual__2024-09-11T04:12:17.707731+00:00, execution_date=20240911T041217, start_date=20240911T041223, end_date=20240911T041225
[2024-09-11T04:12:26.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T04:12:26.614+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task get_op (The conn_id `http_default` isn't defined; 324)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 170, in execute
    return self.execute_sync(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 179, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/operators/http.py", line 152, in hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `http_default` isn't defined
[2024-09-11T04:12:26.794+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-11T04:12:26.812+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T04:12:26.917+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
